# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do
  ENV["locale"] = "UTF-8"
  session = GoogleDrive::Session.from_service_account_key(
    "fastlane-gd-plugin-871dbeb06d3f")
    end

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")

  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    #crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  after_all do |lane|
    upload_to_google_drive(
      drive_keyfile: 'drive_key.json',
      service_account: true,
      folder_id: 'folder_id',
      upload_files: ['README.md']
      )
  end

  error do |lane, exception|

    end


end
